### ISSUE TITLE
send stolen vehicle to impound or place a timer to the owner

### ISSUE THREAD

**Issue by iKaoticx** [RedAlex/esx_ownedcarthief#1]
My ideia is to somehow block the vehicle for the owner after its sold on blackmarket

**Comment by RedAlex** [comment]
We have the same idea.
look this
![pawnshop1](https://user-images.githubusercontent.com/855331/48076225-bca29500-e1b2-11e8-82e0-0cbf86b5777f.jpg)
![pawnshop2](https://user-images.githubusercontent.com/855331/48076226-bca29500-e1b2-11e8-8f1f-dc78d657aa32.png)

**Comment by iKaoticx** [comment]
its already on the alpha 1? do you mind if i DM you on esx dicord?

**Comment by RedAlex** [comment]
Done here https://github.com/RedAlex/esx_ownedcarthief/commit/98d42e7bdbb180540799415d729071ecb5a90a0a
