### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by JonathanFletcher1** [RedAlex/esx_ownedcarthief#4]
Salut Garcio, 

J'ai essayer ton script cependant lorsque j'essaie de voler un vehicules voila l'erreur que j'obtiens 
ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {@plate=28PDW792}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE @plate = plate {=}": Unknown column 'plate' in 'where clause'

**Comment by RedAlex** [comment]
Tu utilise l'ancienne table sql de owned_vehicle. 
La ressource est basé sur la nouvelle table sql de vehicleshop.

You use the old sql table of owned_vehicle
The ressource is based on the new table sql of vehicleshop

**Comment by RedAlex** [comment]
Database a été updater.
